### ISSUE TITLE
Organisation of Workshop

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/zoidbot#14]
people involved: @Jailander @enricodale @apaoli @marc-hanheide @pet1330

see https://github.com/LCAS/zoidbot/wiki/McMan-Industry-Workshop
- [ ] invite people
- [ ] make a flyer (for the NCFM workshop)
- [ ] talk to enterprise for funding and support
- [ ] book lunch
- [ ] prepare demo
- [ ] tidy and set up lab

**Comment by apaoli** [comment]
@marc-hanheide @Jailander @pet1330 @enricodale

Graeme Philp, from Gambica accepted to give a talk! See below.

See you tomorrow,

Andrea

---

Hi Andrea

Thank you for this kind invitation.  I would be delighted to give a talk at the workshop on 27 January.    Would aspects of the talk I gave at the NEC be appropriate for what you are trying to achieve on the day?

Please send further details when you have them.

With best regards

Graeme

**Comment by pet1330** [comment]
I assume this can be closed now? If anyone disagrees, please reopen it.
